MakeContributions/DSA

- README.md
Hi @akrish4  and @paulsonjpaul,
This is related to issue #1
> docs: add contribution-guidelines

- searching/README.md
- sorting/README.md
- strings/README.md
Hi @Arsenic-ATG,
I have added all files to the index using the relative link, please check it out
> docs: add relative path for index

- strings/README.md
- strings/js/palindrome.js
Added palindrome checker for JavaScript. Please check it @ming-tsai, @Arsenic-ATG, @akrish4.
> feat(strings): Add Palindrome Checker for JavaScript

- sorting/README.md
- sorting/js/bubble-sort.js
Add bubble sort JavaScript version
> Add bubble sort JavaScript version

- strings/README.md
- strings/csharp/palindrome.cs
Hi @akrish4 or @Arsenic-ATG ,
Please check it out
> feat(strings): add is palindrome example for C#

- sorting/README.md
- sorting/csharp/bubble-sort.cs
- sorting/csharp/insertion-sort.cs
- sorting/csharp/selection-sort.cs
Hi @Arsenic-ATG,
I added all sorting that we have on C#
> feat(sorting): add csharp examples

- searching/README.md
- searching/java/linear-search.java
I have followed the general guidelines for contribution and left comments about the modifications required to run the code in terminal.
> Add java code for linear search

- sorting/README.md
- sorting/python/insertion-sort.py
- sorting/python/selection-sort.py
Added Insertion and Selection sort for Python. 
I'd be interested in contributing graph search algorithms and possibly other algorithms; I just need to know if you have a desired graph representation or if I can take creative control on the implementation. Thanks.
> Added Insertion and Selection sort to the python folders.

- sorting/js/insertion-sort.js
Hey i added function for insertion sort so it's more readable and reusable.
> improved insertion sort with function style

- CONTRIBUTING.md
- README.md
- contribution.md
@ming-tsai kindly checkout this
> [Docs] Add how to make your First Contributions

- searching/README.md
- searching/js/binary-search-recursive.js
This file contains recursive version of the Binary Search .
> ADD - binary-search-recursive

- strings/README.md
- strings/c-or-cpp/kmp.cpp
- strings/c-or-cpp/rabin-karp.cpp
- strings/java/kmp.java
- strings/java/rabin-karp.java
String searching algorithms in java and c++.
> Add String Search Algorithms in Java & C++

- linked-lists/README.md
- linked-lists/c-or-cpp/reverse-linkedlist.cpp
I have coded a 100% working c++ code with comments for reversing a LinkedList.
Please merge it.
This is my first contribution to an open-source repo yay :)
> adding-reversing-linkedlist

- linked-lists/README.md
- linked-lists/c-or-cpp/circular.cpp
- linked-lists/c-or-cpp/doubly.cpp
Added code for inserting elements in doubly linked list at front.
> Code for inserting elements in doubly linked list

- .github/workflows/greating.yml
Hi 
This PR to add the Welcome action
I hope this be good.
This PR closes #68 
Thanks
> Create Welcome GitHub Action

- graphs/README.md
- graphs/c-or-cpp/kruskal-algorithm.cpp
- linked-lists/README.md
- linked-lists/c-or-cpp/circular.cpp
- linked-lists/c-or-cpp/doubly.cpp
Added Code for Kruskal Algorithm in Graph section.
> Add doubly, circular Linked List, and kruskal graphs

- linked-lists/c-or-cpp/singly.cpp
Hi
Add the `insertAtEnd()` method to single linkedlist.
This PR closes #74 
I hope this be good
Thanks
> Add method to single linkedlist

- stacks/README.md
- stacks/c-or-cpp/balanced-paranthesis.cpp
This is my first ever PR, please forgive me for any mistakes. I thought stacks would be a good topic for this project so I have added it for c-or-cpp. Kindly review and let me know any changes/improvements if needed.
> Add stacks topic for c-or-cpp

- arrays/README.md
- arrays/c-or-cpp/dutch-flag-algo.cpp
Added Dutch flag algo for arrays in CPP section, updated README.md file !!
> Added Dutch Flag algo in Cpp

- arrays/README.md
- arrays/c-or-cpp/left-rotation.cpp
Added a new file under Arrays section i.e. Left rotation using C++.
> added left-rotation.cpp file

- strings/README.md
- strings/python/palindrome.py
Palindrome Check Algorithm in Python (Python 3), using Idiomatic ("Pythonic") Python.
> Add Palindrome Check Algorithm in Python (Idiomatic Python)

- arrays/README.md
- arrays/c-or-cpp/dutch-flag-algo.cpp
Added two different approaches for shifting negative elements in an array , in CPP section!!
> Added  shift-negatives algo in Cpp

- README.md
Added all contributors in the README using [contributors-img](https://contrib.rocks/preview). The image is dynamic i.e. it'll automatically update with new contributions!
> Added contributors in the README

- queues/README.md
- queues/c-or-cpp/queue-linked-list.cpp
Hi 
This PR closes issue #99 
To add the queue data structure
Thanks
> Queue linked-list Added

- queues/README.md
- queues/c-or-cpp/circular-queue-linked-list.cpp
Hi
This PR closes issue #103 
To add the circular queue
I hope this be good
Thanks
> Adding the circular queue

- linked-lists/Python/doubly.py
- linked-lists/Python/singly.py
- linked-lists/README.md
Added  Python code for doubly-linked list
> Python linkedlist

- sorting/README.md
- sorting/go/bubble-sort.go
I added bubble-sort.go algorithm.
No dependencies required.
> bubble-sort.go added

- strings/README.md
- strings/haskell/palindrome.hs
Added palindrome checker in Haskell
> Add Haskell Palindrome

- strings/README.md
- strings/haskell/sequence.hs
Add subSequences in Haskell and fix typo in README.md
> Add Haskell subSequences

- strings/README.md
- strings/c-or-cpp/Permutation of String.c
- strings/c-or-cpp/Permutation-of-String.c
>  Permutation of String

- linked-lists/README.md
- linked-lists/java/doubly.java
> Doubly linked list java

- scheduling/README.md
- scheduling/java/multi-level-queue-scheduling.java
Hi
This PR to add the `Multi-Level Queue Scheduling Algorithm in Java` closes #128 
I hope this be good
> I will add more 3 algorithms soon and fix problems.
Thanks
> Multi-Leve Queue Scheduling Algorithm

- arrays/README.md
- arrays/c-or-cpp/max-subarray-sum.cpp
Added 3 different approaches to calculate max subarray sum!!
> Added max subarray sum in Cpp 

- linked-lists/README.md
- linked-lists/java/circular.java
> Add circular linked list java

- scheduling/README.md
- scheduling/java/round-robin.java
Hi
This PR to add the `Round Robin` Scheduling Algorithm using **Java**
closes #132 
I hope this help others
Thanks
> New scheduling algorithm [Round Robin]

- strings/c-or-cpp/Permutation-of-String.c
hey,
I have done some changes in Permutation of string.c file please review it
> Added Time Complexity and remove single comment into multi comment

- graphs/README.md
- graphs/c-or-cpp/Prim's-algorithm.c
Hey I have added prim's algorithm in c language.
Please review it @Arsenic-ATG and @TawfikYasser 
fixes: #139
> Prim's Algorithm in c

- .github/workflows/lint_python.yml
- linked-lists/c-or-cpp/Insert-and-delete-beginning.c
- sorting/python/bubble-sort.py
Run Python tools bandit, flake8, isort, mypy, pytest, and pyupgrade on every pull request
> GitHub Action to lint Python code

- .github/workflows/cpplint.yml
- linked-lists/c-or-cpp/doubly.cpp
- multiplication/c-or-cpp/karatsuba.cpp
- strings/c-or-cpp/string-tokeniser.cpp
GitHub Action to run [cpplint](https://github.com/cpplint/cpplint) recursively on all pushes and pull requests
https://github.com/cpplint/GitHub-Action-for-cpplint
% `cpplint --counting=detailed --recursive .`
```
Category 'build/c++11' errors found: 1          // Fixed in this pull request
Category 'build/include_order' errors found: 2  // Fixed in this pull request
Category 'build/namespaces' errors found: 36
Category 'legal/copyright' errors found: 46
Category 'readability/braces' errors found: 16
Category 'readability/casting' errors found: 5
Category 'readability/utf8' errors found: 52
Category 'runtime/arrays' errors found: 12
Category 'runtime/explicit' errors found: 3
Category 'runtime/int' errors found: 7
Category 'runtime/printf' errors found: 1
Category 'runtime/references' …
```
> GitHub Action to lint C and C++ code

- arrays/README.md
- arrays/java/left_rotation.java
adding left rotation algorithm in java and link it in the README.md
> add arrays left rotation in java

- arrays/python/count-inversions.py
These [doctests](https://docs.python.org/3/library/doctest.html) can be run with `python3 -m doctest -v count-inversions.py`
Our GitHub Actions will also run these doctests.  https://github.com/MakeContributions/DSA/actions
The answer to the last test should be 0, not 2.  The algorithm is currently counting inversions that are not required.
@atin Your review please.
> Add Python doctests to count-inversions.py

- sorting/python/quick-sort.py
> Add Python doctests to quicksort.py

- scheduling/python/interval-scheduling.py
I do not understand the output of this algorithm.  Is there a URL that explains its results?
`[5, 4, 1, 7]` shows that the optimal schedule is four batches but which jobs should be run in each batch?
A [namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) would improve the readability of the code...
```
from collections import namedtuple
Job = namedtuple("Job", "job_id start_time finish_time")
```
@atin Your review, please.
> Add Python doctest to interval-scheduling.py

- strings/python/palindrome.py
Updates #169 
@cclauss @Arsenic-ATG review please.
> Added doctest in palindrome.py

- .github/workflows/lint_python.yml
> chore: add ignore word

- linked-lists/README.md
- linked-lists/java/reverse.java
changes 
* add reverse.java file
*  link the file to readme.md
> Add reverse linked list in java

- trees/README.md
- trees/java/pre_in_post_traversal.java
changes and additions ;
* add pre_in_post_traversal.java file
* link the file in readme.md
> Add trees pre in post traversal java

- graphs/README.md
- graphs/java/Dijkstras.java
I have addded the code for Dijkstras Algorithm graphs/java/.
The input is a a hardcoded graph which can be converted to user I/O by modifying the createGraph function.
> Added Java Implementation of Dijkstras Algorithm for Single Source Shortest Path

- strings/README.md
- strings/java/tokenizer.java
* new file tokenizer.java
* link the file in readme.md
tokenize(str, delimiters)
* **str** : is a text
* **delimiters** : is a list of char which is by default white space  ' '
exemple: 
```
tokenize("hello world") = tokenize("hello world", ' ') = [ 'hello', 'world' ]
tokenize("hello world", ' ', 'l') = [ 'he', 'o', 'wor', 'd' ]
```
> Added string tokenizer in java

- strings/README.md
- strings/js/sequence.js
add sequence.js
and link to readme.md
> Added string subsequence in JS

- strings/java/paindrome.java
- strings/java/palindrome.java
add function to check palindrome considering ( or not) uppercases
rename the file from paindrome to palindrome
> Java palindrome case sentitive

- algorithms/Java/README.md
- stacks/README.md
updated README.md
closes: #224
> fix dead links in stacks folder

- algorithms/C/README.md
- algorithms/C/sorting/insertion-sort.c
Hey,
I have added Insertion Sort in c 
Please review it 
closes: #233 
Thanks
> Added Insertion Sort in c

- algorithms/C/README.md
- algorithms/C/searching/Binary-search.c
Hey @ming-tsai ,
I have added binary search in c
Please review it 
closes: #248 
Thanks
> added binary search.c

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/sorting/merge-sort.js
Added merge sort implementation in JavaScript.
> add merge-sort

- algorithms/Java/README.md
- algorithms/Java/sorting/shell-sort.java
> chore(Java): add shell sort

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/index.js
- algorithms/JavaScript/src/sorting/quick-sort.js
QUICK SORT ADDED FOR JAVASCRIPT
> chore(JavaScript): quick sort added

- algorithms/Java/README.md
- algorithms/Java/linked-lists/fold-linked-list.java
> chore(Java): add fold-linked-list

- algorithms/C/README.md
- algorithms/C/searching/Jump-search.c
- algorithms/CPlusPlus/Searching/jump-search.cpp
Added jump search in c language and modified jump search in c++
closes #258 
Thanks
> enh: jump search in C and C++

- algorithms/C/README.md
- algorithms/C/sorting/bubble-sort.c
Bubble sort for C language: https://onlinegdb.com/SJeYlj94wO
> chore(C): Add bubble sorting for C language

- algorithms/Python/README.md
- algorithms/Python/searching/ternary_search.py
Added ternary search in python. 
Source: https://cp-algorithms.com/num_methods/ternary_search.html
It is similar to Binary Search and is often considered to be a kind of optimization of the same.
> chore(Python): added ternary_search

- algorithms/CPlusPlus/README.md
Fix link to the **all-possible-insertion.cpp** in the README.md and Add **merge.cpp** to the README.md under **CPlusPlus** directory
> docs: fix typo

- algorithms/C/README.md
- algorithms/C/searching/Ternary-search.c
- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Searching/Ternary-search.cpp
Added Ternary Search in c and c++ language and also updated the readme of c and CPP
closes: #277
> chore(C & CPP): Ternary Search

- algorithms/Java/README.md
- algorithms/Java/stacks/celebrity-problem.java
- algorithms/Java/stacks/sliding-window-maximum.java
> chore(Java): add Celebrity Problem and Sliding Window Maximum

- algorithms/C/README.md
- algorithms/C/sorting/heap-sort.c
added heap sort in C
**Others information**
It's my first time opening a pull request
> chore(C): add Heap-sort

- algorithms/CPlusPlus/Sorting/heap-sort.cpp
Added test case and time complexity along with changes in the code.
> enh(CPlusPlus): heap-sort

- algorithms/CPlusPlus/Arrays/reverse-array.cpp
- algorithms/CPlusPlus/README.md
Added reverse-array file
This add new file to the cpp section.
> chore(CPlusPlus): create reverse-array.cpp

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Trees/binary-search-tree.cpp
Binary search tree algorithm in c++ and update that in README.md
> chore(CPlusPlus): add binary search tree

- algorithms/CPlusPlus/Maths/prime-check.cpp
- algorithms/CPlusPlus/README.md
Added new file in Maths section(prime-check.cpp).
> chore(CPlusPlus): created prime-check

- algorithms/C/searching/linearsearch.c
> chore(C): add linear search

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/linked-lists/doubly.js
Add doubly linked list of Javasciprt.
> chore(Javascript): add doubly linked-list

- algorithms/Python/README.md
- algorithms/Python/sorting/heap-sort.py
> chore(Python): create heap-sort

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Sorting/binary-insertion-sort.cpp
Insertion sort that utilizes binary search algorithm
> chore(CPlusPlus):  add binary insertion sort

- algorithms/Python/README.md
- algorithms/Python/arrays/majority_element.py
- algorithms/Python/arrays/missing_number.py
- algorithms/Python/arrays/rotate_array.py
- [ x] New algorithm
Added 3 new coding problems which are standard for new coders.
1. Rotate Array: rotating an array based on an input k
2. Majority Element problem based on Boyer Moore Algorithm
3. Missing Element: based on basic question of sum of natural numbers
Will be adding some more codes and new pull requests in recent upcoming days.
> chore(Python): add sankalp arrays

- algorithms/CPlusPlus/Maths/prime-sieve.cpp
- algorithms/CPlusPlus/README.md
Algorithm to print  `prime numbers` within range  (0 to number) .
> chore(CPlusPlus): add prime-sieve algorithm

- algorithms/Python/README.md
- algorithms/Python/strings/first_non_repeating_character.py
- algorithms/Python/strings/remove_duplicates_from_a_string.py
Added two new strings based algorithms/solutions for Python.
Algorithm 1: Remove Duplicates from a string (using 26character string instead of set/dictionaries)
Algorithm 2: First non repeating character in a string (without using dictionary)
Updated the readme accordingly.
> chore(Python): add  remove duplicate and first non-repeating character string

- algorithms/Java/README.md
- algorithms/Java/trees/right-view.java
Implemented RIght view of a binary tree with iterative as well as recursive approach
> chore(Java): Right view of tree

- algorithms/CPlusPlus/Arrays/search-sorted-rotated.cpp
- algorithms/CPlusPlus/README.md
Searching element in the sorted-rotated array
> chore(CPlusPlus): add search sorted rotated

- algorithms/CPlusPlus/Trees/binary-search-tree.cpp
Add functions to check if a binary tree is full and perfect
> enh(CPlusPlus): add functions to binary-search-tree

- algorithms/Java/README.md
- algorithms/Java/trees/zig-zag-traversal.java
Implemented Zig-Zag Traversal of a Tree using Stacks.
> chore(Java): Zig-Zag Traversal of a Tree

- algorithms/Java/sorting/bubble-sort.java
> enh(Java): more optimized way of bubble-sort

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Sorting/merge-sort.cpp
Added merge sort algorithm to C++ sorting folder
> chore(CPlusPlus): created merge-sort

- algorithms/Python/README.md
- algorithms/Python/sorting/radix_sort.py
- Added radix sort program in python
> chore(Python): added radix sort program

- algorithms/C/README.md
- algorithms/C/linked-lists/Insert-and-del-beginning-circular-ll.c
Added Circular Linked List Program in C language
> chore(C): add circular linked list

- algorithms/Python/README.md
- algorithms/Python/sorting/shell-sort.py
added shell sort in sorting category of python 
updated readme too
> chore(Python): shell sort algorithm

- algorithms/Python/README.md
- algorithms/Python/searching/interpolation_search.py
Added interpolation search, in Python
> chore(Python): added interpolation search file

- algorithms/C/README.md
- algorithms/C/searching/Interpolation-search.c
I have added an Interpolation search using the c language and also modified the readme.MD of C folder
closes: #284
> chore(C): added Interpolation Search

- algorithms/Python/README.md
- algorithms/Python/dynamic_programming/catalan_sequence.py
Prints the first n terms of the Catalan sequence
NA
> chore(Python): added catalan sequence

- algorithms/Python/README.md
Updated the Python/Readme.md file so that the link to Catalan Sequence links to the script. 
NA
> fix(Python): catalan sequence URL

- algorithms/Java/Maths/factorial_using_big_integer.java
- algorithms/Java/README.md
I have added Factorial of a Number using BigInteger in Java.
> chore(Java): add factorial of a number using Big Integer

- algorithms/Python/README.md
- algorithms/Python/sorting/merge_sort.py
I want to add the merge_sort algorithm into this repositry. I have coded it in python and I forked it.
I would like to contribute more to this repository.
> chore(Python): added Merge Sort algorithm

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Strings/anagram.cpp
> chore(CPlusPlus): created anagram

- algorithms/C/README.md
- algorithms/C/linked-lists/merge-two-linkedlists.c
- algorithms/C/linked-lists/reverse-linkedlists.c
I added two new algorithms using **C language**. 
1. Merge two linked-lists:
This algorithm will merge two linked-lists. That is, it will append one linked-list to the end of another linked-list.
2. Reverse a linked-list:
This algorithm will reverse the given linked-list. See this article for more info [Reverse a linked list](https://www.geeksforgeeks.org/reverse-a-linked-list/)
And I added my new algorithms in the README.md of the **C** folder.
> chore(C): add reverse and merge linked lists

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Trees/min-heap.cpp
> chore(CPlusPlus): add min-heap

- algorithms/C/README.md
- algorithms/C/bit-manipulation/add-and-sub-bitwise.c
- algorithms/C/bit-manipulation/divide-bitwise.c
- algorithms/C/bit-manipulation/multiply-bitwise.c
Added three files in the directory bit-manipulation 
- Add and Subtract two integers without using a '+' operator. 
- Multiply two integers without using a '*' operator. 
- Divide two integers without using a '/' operator.
> chore(C): added bit-manipulation

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Stacks/stack-using-array.cpp
added Stack using array in c++ folder and update the readme of it
closes: #341
> chore(CPlusPlus): add stack using array

- algorithms/Java/README.md
- algorithms/Java/arrays/majority-element.java
Implementing a program to find Majority Element in Java
Using  Moore’s Voting Algorithm!
> chore(java): add majority element

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Searching/exponential-search.cpp
> chore(CPlusPlus): add exponential search

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Maths/abundant-number.cs
- algorithms/CSharp/test/Maths/AbundantTestUnit
Created a folder name: `Maths` in CSharp/src dir and added the solution.cs there
closes: #355
> chore(csharp): Abundant Number

- .github/ISSUE_TEMPLATE/proposal.md
Added proposal.MD in .github folder
Related issue: #249
> docs(template): create proposal issue

- algorithms/CPlusPlus/Graphs/breadth-first-search.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): added breadth first search

- algorithms/Java/README.md
- algorithms/Java/arrays/kth-element-2sorted-array.java
Implement the Kth element of two sorted arrays.
> chore(Java): add k-th element of 2 sorted arrays

- algorithms/Java/README.md
- algorithms/Java/arrays/trapping-rain-water.java
Implement a program to find Trapped rain water
> chore(Java): add Trapped Rain Water

- algorithms/CPlusPlus/Maths/fibonaccci-series.cpp
- algorithms/CPlusPlus/Maths/fibonacci-series.cpp
- algorithms/CPlusPlus/README.md
Added a class in C++ that calculates a defined number of the fibonaccci serie. The number of digits calculated is defined by the user.
> chore(CPlusPlus): add fibonacci series

- algorithms/CPlusPlus/Linked-Lists/Reorder-List.cpp
- algorithms/CPlusPlus/README.md
Added Reorder List program in Algorithm/Linked-Lists/Reorder-List
closes: #363
> chore(CPlusPlus): add Reorder list

- algorithms/CPlusPlus/Linked-Lists/circular.cpp
This refactors the previous code to make it more readable and user friendly
Changes are still not final, I will make the changes soon
> enh(CPlusPlus): circular linked lists

- algorithms/C/README.md
- algorithms/C/tree/avl-tree.c
> chore(C): add avl tree

- algorithms/CPlusPlus/Graphs/topological-sort.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): topological sort on graphs

- algorithms/CPlusPlus/Stacks/balanced-parenthesis.cpp
add a proper comment in the program and replace the switch statement with the if statement as switch cases do the same work that only one if condition does as well as make the program much more user friendly by providing a better UI than before
closes: #375
> enh(CPlusPlus): balanced-parenthesis

- algorithms/C/README.md
- algorithms/C/tree/max-heap.c
- algorithms/C/tree/min-heap.c
min heap and max heap in c
Issue: #385
> chore(C): add min and max heap

- algorithms/CSharp/Algorithms.sln
- algorithms/CSharp/README.md
- algorithms/CSharp/src/Search/linear-search.cs
- algorithms/CSharp/test/Search/linear-search.cs
Added a new linear search algorithm (C#). Created unit tests for the algorithm and updated the README to reflect the newly added algorithm
> chore(CSharp):  added linear search algorithm

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Recursion/towerofHanoi.cpp
> chore(CPlusPlus): added tower of hanoi in recursion

- algorithms/C/README.md
- algorithms/C/sorting/selection-sort.c
> chore(C): add selection sort

- .gitignore
- algorithms/Rust/README.md
- algorithms/Rust/sorting/merge-sort/.gitignore
- algorithms/Rust/sorting/merge-sort/Cargo.toml
- algorithms/Rust/sorting/merge-sort/README.md
- algorithms/Rust/sorting/merge-sort/src/main.rs
Add rust files to gitignore
Implemented merge sort in rust. [Merge Sort Background](https://en.wikipedia.org/wiki/Merge_sort)
> chore(Rust): add merge sort

- algorithms/CPlusPlus/Dynamic-Programming/01-knapsack.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add 0/1 Knapsack problem to Dynamic Programming

- algorithms/Java/README.md
- algorithms/Java/strings/anagram.java
- Added a string anagram algorithm in java.
> chore(Java): added anagram

- algorithms/CPlusPlus/Arrays/quick-select.cpp
- algorithms/CPlusPlus/README.md
I have added a new algorithm popularly known as the "quick-select" or Partition algorithm.
> chore(CPlusPlus): add quick-select

- algorithms/CPlusPlus/Dynamic-Programming/longest-common-subsequence.cpp
- algorithms/CPlusPlus/Dynamic-Programming/longest-common-substring.cpp
- algorithms/CPlusPlus/README.md
Longest common substring using Dynamic Programming in C++
> chore(CPlusPlus): adding longest common substring

- algorithms/CPlusPlus/Dynamic-Programming/matrix-chain-multiplication.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add Matrix Chain Multiplication to Dynamic Programming

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Recursion/factorial.cpp
- algorithms/Python/README.md
- algorithms/Python/recursion/factorial.py
1. Added recursive folder to Python with factorial.py inside
2. Added factorial.cpp to Recursive folder in CPlusPlus folder (new file, but the folder has been created before)
3. Modified README.md in CPlusPlus folder to include factorial
This is my first time participating in this pull request; so I decided to try with a simple topic to test the water. I will definitely contribute more once I fully understand the workflow of this repository. I will mostly contribute using C++ and Python. Please let me know if I need to modify something as I usually open GitHub on a daily basis, so you can expect a quick response from me.
> chore: add recursion factorial C++ and Python

- algorithms/CPlusPlus/Arrays/remove-duplicates.cpp
- algorithms/CPlusPlus/README.md
Algorithm: Remove duplicate elements from array in place without using an extra space
language used: cpp
> chore(CPlusPlus): added remove-duplicates

- algorithms/CPlusPlus/Trees/binary-search-tree.cpp
- algorithms/CPlusPlus/Trees/pre-in-post-traversal.cpp
1. I have added iterative method also for traversal of tree using stak for better understanding.
2. I have added three functions in Binary search tree : finding maximum, minimum value in a BST and printing all lead nodes present in the tree.
> enh(CPlusPlus): Binary Search Tree and Iterative Traversal

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Algorithms.csproj
- algorithms/CSharp/src/Recursion/factorial.cs
- algorithms/CSharp/test/Recursion/factorial.cs
Added a new algorithm (C#) for determining the factorial of a number. Created unit tests for the algorithm and updated the README to reflect the newly added algorithm
> chore(CSharp): added algorithm to determine factorial 

- algorithms/CPlusPlus/Arrays/leaders-in-array.cpp
- algorithms/CPlusPlus/README.md
This is the C++ code to print leaders in an array. If an element is greater than all the elements to its right, the element is a leader.
Language used: C++
Method: From right to left in the array, scan all elements and record the maximum element until now. When the maximum element changes, print it.
Time Complexity: O(n)
> chore(CPlusPlus): add leaders in arrays

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Graph/depth-first-search.cs
- algorithms/CSharp/test/Graph/depth-first-search.cs
> chore(CSharp): add Depth First Search

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Sorting/cycle-sort.cpp
I had added New algorithm i.e Cycle Sort in the sorting algorithm in CPlusPlus language. It was not available there.  
This sorting algorithm is best suited for situations where memory write or swap operations are costly.
> chore(CPlusPlus): add cycle-sort

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Queues/queue-implementation-using-two-stacks.cs
- algorithms/CSharp/test/Queues/queue-implementation-using-two-stacks.cs
Added queue implementation using two stacks.
> chore(CSharp): add implementation of queue using two stacks

- algorithms/CPlusPlus/Linked-Lists/segregate-even-odd-nodes-of-linked-list.cpp
- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Sorting/cycle-sort.cpp
I had added Segregate even-odd nodes of linked list in the linked list algorithm in CPlusPlus language. It was not available there.
> chore(CPlusPlus): add segregate-even-odd-nodes-of-linked list

- algorithms/CPlusPlus/Dynamic-Programming/edit-distance.cpp
- algorithms/CPlusPlus/README.md
I have added program to find out minimum number of edits required to convert one string to another.
> chore(CPlusPlus): Add Edit Distance

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Sorts/counting-sort.cs
- algorithms/CSharp/test/Sorts/counting-sort.cs
Added counting sort. Refactored a typo in the Readme
> chore(CSharp): Added counting sort 

- algorithms/C/README.md
- algorithms/C/linked-lists/doubly-linked-list.c
add doubly linked list using C
> chore(C): add doubly linked list

- .gitignore
- algorithms/Python/README.md
- algorithms/Python/strings/unique_character.py
Added  algorithm to check whether the given string has unique characters or not
Algorithm is written in python language. 
> chore(Python): added is unique character algorithm

- docs/en/README.md
- docs/en/Sorting/Heap-Sort.md
- Added the documentation of heap sort algorithm.
- Added the link of heap sort documentation to README.md.
> docs: add heap sort

- algorithms/CPlusPlus/Arrays/maximum-difference.cpp
- algorithms/CPlusPlus/README.md
This program finds the maximum difference between two elements in an array such that larger element appears after the smaller number in C++.
> chore(CPlusPlus): add maximum difference

- algorithms/CPlusPlus/Arrays/Elements_appears_thrice.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add elements appear thrice

- docs/en/README.md
- docs/en/Sorting/Quick-Sort.md
- Added the documentation of quick sort algorithm.
- Added the link of quick sort documentation to README.md.
> docs: add quick sort

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Strings/delete-alternate-characters.cpp
- algorithms/CPlusPlus/Strings/print-first-letter.cpp
> chore(CPlusPlus): delete alternate characters in a string

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Graph/kruskals-algorithm.cs
- algorithms/CSharp/test/Graph/kruskals-algortihm.cs
added implementation of Kruskals algorithm with test cases.
> chore(CSharp): added kruskals algorithm

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Sorts/merge-sort.cs
- algorithms/CSharp/test/Sorts/merge-sort.cs
- docs/en/Sorting/Merge-Sort.md
added merge sort implementation with unit test
> chore(CSharp): added merge sort

- algorithms/Python/README.md
- algorithms/Python/linked_lists/reverse-linkedlist.py
Added algorithm to reverse a linked list
> chore(Python): added reverse linked list

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Arrays/single-number.cs
- algorithms/CSharp/test/Arrays/single-number.cs
Added single number determination with unit tests.
> chore(CSharp): added single number determination

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Algorithms.csproj
- algorithms/CSharp/src/Graph/dijkstra.cs
- algorithms/CSharp/test/Graph/dijkstra.cs
Added Dijkstras algo with unit tests
> chore(CSharp): Implemented Dijkstras Algorithm to Find the Shortest Path

- algorithms/CPlusPlus/Maths/reverse-digits.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add reverse digits

- algorithms/Python/README.md
- algorithms/Python/trees/binary-search-tree.py
+ ### added binary-search-tree algorithm
> chore(Python): added binary search tree

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Number-Theory/big-mod.cs
- algorithms/CSharp/test/Number-Theory/big-mod.cs
added big mod algorithm with unit tests
> chore(CSharp): Added Big Mod Algorithm

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Number-Theory/sieve-of-eratosthenes.cs
- algorithms/CSharp/test/Number-Theory/sieve-of-eratosthenes.cs
Added Sieve of Eratosthenes to generate primes from 1 to N
> chore(CSharp): Added Sieve of Eratosthenes to generate primes from 1 to N

- algorithms/C/README.md
- algorithms/C/linked-lists/gl-threads.c
In traditional a doubly linked-list each node will have a left and right pointer and a pointer to the data, so the structure of the node will contain 3 data members(next, prev, data). In Glue based doubly linked-list there will only be 2 data members left and right pointers. As for the data, it will be glued on top of the node.
> chore(C): add glued doubly linked-list

- docs/en/README.md
- docs/en/Searching/Linear-Search.md
Added Linear Search Algorithm documentation in English according to the template given.
>  docs(en): added linear-search

- algorithms/CPlusPlus/Maths/factorial.cpp
- algorithms/CPlusPlus/Maths/missing-number.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): added math factorial

- algorithms/CSharp/src/Number-Theory/sieve-of-eratosthenes.cs
- algorithms/CSharp/test/Number-Theory/sieve-of-eratosthenes.cs
> refact(CSharp): rename from PrimeGenerator to GeneratePrimeNumbers

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Number-Theory/bitwise-sieve-of-eratosthenes.cs
- algorithms/CSharp/test/Number-Theory/bitwise-sieve-of-eratosthenes.cs
Implemented Bitwise Sieve of Eratosthenes
> chore(CSharp): Implemented Bitwise Sieve of Eratosthenes

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Graph/floyd-warshall-algorithm.cs
- algorithms/CSharp/test/Graph/floyd-warshall-algorithm.cs
Added Floyd Warshall Algorithm with unit tests
> chore(CSharp): Added Floyd Warshall Algorithm

- algorithms/CPlusPlus/Arrays/search-insert-position.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): added search insert position

- algorithms/JavaScript/src/linked-lists/singly.js
Following functionality was added to single link list
- Getting a particular node from link list by index.
-  Changing the value of a particular node in link list by index.
-  Inserting after a particular node by specifying index and the value to be inserted.
-  Removing a particular node from middle of the link list.
- 
> enh(JavaScript): add getByIndex and insertAfterByIndex on singly linked list

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Strings/longest-name.cpp
> chore(CPlusPlus): display longest name

- algorithms/Java/README.md
- algorithms/Java/searching/interpolation-search.java
Added Interpolation Search in java under Searching algorithms
> chore(Java): added interpolation search

- algorithms/CPlusPlus/Graphs/dijkstra.cpp
- algorithms/CPlusPlus/README.md
Implementation of Dijkstra's algorithm in c++.
Returns the cost(distance) of the shortest path from start to end in a given directed graph.
> chore(CPlusPlus): add dijkstra graphs

- .vscode/settings.json
- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Strings/first-unique-character.cpp
- algorithms/CPlusPlus/Strings/longest-common-prefix.cpp
> chore(CPlusPlus): add longest common prefix and first unique character

- algorithms/JavaScript/src/linked-lists/doubly.js
Reference Issue : #628 
This PR refactors doubly link list in javascript, to accurately reflect the instance of DLL.
Please refer the Issue no. mentioned above for any additional details regarding the same.
None
> enh(JavaScription): refactor doubly link list

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Recursion/linear-search.cpp
- algorithms/CPlusPlus/Searching/linear-search-in-2d.cpp
> chore(CPlusPlus): add linear search for recursion and two dimension array 

- algorithms/Java/README.md
- algorithms/Java/stacks/Min-Stack.java
> chore(Java): add finding min value on stack

- algorithms/Java/Maths/algorithms_random_node.java
- algorithms/Java/README.md
Add an easy and efficient code to find a random node in a given linked list. A file 'algorithms_random_node' has been added in the Maths section of the JAVA language. Readme.md has been updated as well!
Description , Algorithm , test cases and time complexity has been provided as comments in the file.
Screenshots of the output :
> chore(Java): add random node in linked list

- algorithms/JavaScript/src/sorting/bubble-sort.js
File Name : [bubble sort](algorithms/JavaScript/src/sorting/bubble-sort.js)
This pull request fixes the bug in bubble sort and returns a sorted array as per bubble sort theory.
Reference Issue : #646 
> fix(Javascript): bubble sort

- algorithms/JavaScript/src/searching/binary-search-recursive.js
- algorithms/JavaScript/src/searching/binary-search.js
> enh(JavaScript): binary-search

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Stacks/stock-span-problem.cpp
Stock Span Problem in O(n) using Stacks in C++
> chore(CPlusPlus): add stock span problem

- algorithms/C/README.md
- algorithms/C/sorting/quick-sort.c
> chore(C): add quick sort

- algorithms/Python/README.md
- algorithms/Python/dictionaries/two-sum.py
…algorithms/python/dictionaries
> chore(Python): add two sum for Dictionaries

- algorithms/JavaScript/src/sorting/selection-sort.js
Delay the swapping until we find the minimum element in the unsorted section of the array
> enh(Javascript): Delay swapping

- algorithms/C/README.md
- algorithms/C/stacks/stack-using-arrays.c
- algorithms/C/stacks/stack-using-linked-list.c
Added Stack Using Arrays and Linked List.
> chore(C): add stacks arrays and linked list

- algorithms/Java/README.md
- algorithms/Java/trees/tree-random-node.java
Add an easy and efficient code to find a random node in a given Binary Tree. A file 'tree-random-node' has been added in the Trees section of the JAVA language. Readme.md has been updated as well!
Description, Algorithm, Explanation, test cases and time complexity have been provided as comments in the file.
Screenshots of the Output :
> chore(Java): add random node in a binary tree

- algorithms/Python/recursion/factorial.py
This is the update of factorial.py to provide standard of the clean codes.
> enh(Python): rename from FactorialNonRecursion to factorial_nonrecursion

- algorithms/Python/README.md
- algorithms/Python/recursion/factorial.py
- algorithms/Python/trees/binary_search_tree.py
- algorithms/Python/trees/binary_tree.py
> enh(Python): binary tree

- algorithms/Python/recursion/recursive_insertion_sort.py
> enh(Python): rename from insertionSort_rec to insertion_sort_rec

- algorithms/CPlusPlus/Maths/power-of-two.cpp
How to check power of two using Binary Method in O(1) Time Complexity.
> enh(CPlusPlus): add missing space to power-of-two maths

- algorithms/C/README.md
- algorithms/C/maths/fibonacci-series.c
I have added fibonacci series in C.
> chore(C): add fibonacci series

- algorithms/CPlusPlus/Stacks/stock-span-problem.cpp
> enh(CPlusPlus): fix indent stock span problem

- algorithms/C/README.md
- algorithms/C/recursion/tower-of-hanoi.c
Add tower of hanoi using recursion in C
> chore(C): add tower of Hanoi using recursion

- algorithms/C/README.md
- algorithms/C/sorting/shell-sort.c
> chore(C): add shell sort

- algorithms/Python/README.md
- algorithms/Python/dynamic_programming/levenshtein_distance.py
I implemented Levenshtein Algorithm in Python using naive recursive approach.
> chore(Python): add Levenshtein distance

- README.md
- docs/pt/CONTRIBUTING.md
- docs/pt/Procura/Pesquisa-Binaria.md
- docs/pt/README.md
- docs/pt/Strings/Palindrome.md
Added the portuguese language so CPLP(Community of Portuguese Language Countries) can make contribute.
Made the two initial files(CONTIBUTING.md and README.md) in portuguese so CPLP can start contribute to the repository.
> docs: add Português language

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Stacks/prefix_to_postfix.cpp
> chore(CPlusPlus): add prefix to postfix stacks

- algorithms/Python/README.md
- algorithms/Python/queues/FIFOqueue.py
- algorithms/Python/queues/fifo-queue.py
Added the code for a first in first out queue
> chore(Python): add first in first out queue

- algorithms/Python/linked_lists/singly.py
Added insertion and deletion functionality in Linked List, in Python.
> enh(Python): add insert end function on singly linked list

- algorithms/C/README.md
- algorithms/C/arrays/largestElement.c
> chore(C): add largestElement in array

- algorithms/CPlusPlus/Dynamic-Programming/fibonacci.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add fibonacci

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Trees/sum-of-right-leaves.cpp
Added algorithm to recursively traverse through a binary tree to get the sum of all right leaves
> chore(CPlusPlus): add sum of right leaves in binary tree

- algorithms/CPlusPlus/Graphs/cycle-detection.cpp
- algorithms/CPlusPlus/README.md
Added graph cycle detection using the union-find algorithm in C++.
> chore(CPlusPlus): add cycle detection

- algorithms/Python/README.md
- algorithms/Python/strings/rabin-karp-algorithm.py
Added a new algorithm, Rabin-Karp pattern matching algorithm implemented in python
> chore(Python): add Rabin Karp algorithm

- algorithms/Python/README.md
- algorithms/Python/linked_lists/middle-node-linkedlist.py
> chore(Python): add program to print middle node element of linked list

- algorithms/CPlusPlus/Number system/.gitignore
- algorithms/CPlusPlus/Number system/binary_addition.cpp
- algorithms/CPlusPlus/Number system/binary_to_decimal.cpp
- algorithms/CPlusPlus/Number system/decimal_to_binary.cpp
- algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp
- algorithms/CPlusPlus/Number system/decimal_to_octal.cpp
- algorithms/CPlusPlus/Number system/hexa_to_decimal.cpp
- algorithms/CPlusPlus/Number system/octal_to_decimal.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add number system

- algorithms/CPlusPlus/Graphs/kruskal-algorithm.cpp
Added a function to create new instances or updates easily and decrease the redundancy of code.
> enh(CPlusPlus): add helps function on kruskal algorithm

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Search/minima-maxima.cs
- algorithms/CSharp/test/Search/minima-maxima.cs
Minima Maxima is a searching algorithm to find local and global minima and maxima in a list of numbers
> chore(CSharp): add minima maxima

- docs/en/Sorting/Radix-Sort.md
I have added doc for Radix sort implemented in different languages..
> docs: add radix sort

- algorithms/Python/README.md
- algorithms/Python/arrays/dutch_national_flag_algo.py
> chore(Python): add dutch national flag algo

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Strings/character-limit.cs
- algorithms/CSharp/test/Strings/character-limit.cs
Character_Limit allows a user to enter a string and determine how many characters in that string will be shown before it continues with periods. For example, entering in "Hello" and limiting the character limit to 2 will out put "He..."
> chore(CSharp): add character limit

- .github/workflows/codespell.yml
> fix(codespell): C# test folder ignore path

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/index.js
- algorithms/JavaScript/src/maths/fibonacci-series.js
It's my first contribution to the project, hopefully I did everything right. I created a new folder in the javascript folder called "maths" for all math-related algos, and created a first one for the fibonacci series. If did anything wrong and needs changing please let me know and I will try and fix it asap.
Thank you
> chore(Javascript): add fibonacci series

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/index.js
- algorithms/JavaScript/src/recursion/factorial.js
- package-lock.json
I added an algorithm to the JS folder to calculate factorial of n using recursion, also added it to the language readme
> chore(Javascript): add factorial recursion

- algorithms/CSharp/README.md
**What kind of change does this PR introduce?** 
Documentation
**Brief description of PR**
> docs(CSharp): grammar enhancement

- algorithms/Python/README.md
- recursive-sum-of-n-numbers.py
> chore(Python): add sum of n numbers using recursion

- algorithms/CPlusPlus/Searching/binary-search.cpp
Improved the code by adding the explanation of using  (l + (r - l)) rather than using (l - r) while searching for the mid element.
> enh(CPlusPlus): add binary search

- algorithms/Java/searching/binary-search.java
Improved the code by adding the explanation of using  (l + (r - l)) rather than using (l - r) while searching for the mid element.
> enh(Java): add comments for binary search

- algorithms/C/README.md
- algorithms/C/arrays/sieve-of-eratosthenes.c
algorithm
Algorithm name: Sieve of Eratosthenes
language used to implement: C
link to online implementation: https://pastebin.com/5jqMLdyu
> chore(C): add sieve-of-eratosthenes

- README.md
- docs/es/CONTRIBUTING.md
- docs/es/Ordenamiento/Quick-Sort.md
- docs/es/README.md
Add folder structure for Spanish translations and the explanation for the Quick Sort algorithm.
> docs(Spanish): add quick sort

- algorithms/C/maths/fibonacci-number/src/fib.c
- algorithms/C/maths/fibonacci-number/src/fib.h
- algorithms/C/maths/fibonacci-number/src/main.c
- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Recursion/reverse-a-number.cpp
> chore(CPlusPlus): add reverse number algorithm

- algorithms/CSharp/README.md
- algorithms/CSharp/src/Sorts/quick-sort.cs
- algorithms/CSharp/test/Sorts/quick-sort.cs
Add Quick Sort implementation for C#.
> chore(CSharp): add quick sort

- docs/en/README.md
- docs/en/Sorting/Cycle-Sort.md
I have added Cycle Sort Algorithm description in the docs folder
> docs(en): add cycle sort

- algorithms/Python/README.md
- algorithms/Python/number_theory/prime_number.py
> chore(Python) : add prime number check

- algorithms/CPlusPlus/Searching/binary-search.cpp
Modified 
Line 10:
Fixed the typo
```diff
- (l - r)
+ (l + r)
```
And Line 18:
Changed the comment to match with the code implementation - `if (arr[mid] > x)`
```diff
- // If element is smaller than mid
+ // If mid is greater than element
```
Improved comments in binary-search.cpp,
> enh(CPlusPlus): update comment of binary search

- algorithms/Python/README.md
The heading for Number theory was corrected and correct link for prime number checker was added
> docs(Python): add missing space on README

- docs/en/Lists/doubly-linked-list.md
- docs/en/README.md
Add docs(en) for doubly linked list. 
Addresses #docs(en): doubly-linked-list
Please, review.
> docs(en): add doubly linked list

- docs/es/Ordenamiento/Merge-Sort.md
- docs/es/README.md
Add spanish translation for the Merge Sort algorithm.
> docs(Spanish): add merge sort

- algorithms/Go/README.md
- algorithms/Go/sorting/selection-sort.go
> chore(Go): add selection sort

- algorithms/CPlusPlus/Graphs/floyd-warshall.cpp
- algorithms/CPlusPlus/README.md
Added floyd warshall algorithm in CPlusPlus that is used to calculate all pairs shortest paths.
> chore(CPlusPlus): add Floyd Warshall algorithm

- algorithms/CPlusPlus/Arrays/sparse_matrix.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add sparse matrix

- algorithms/CPlusPlus/Graphs/prim's_algorithm.cpp
- algorithms/CPlusPlus/README.md
> chore(CPlusPlus): add prim's graph algorithm

- algorithms/C/README.md
- algorithms/C/arrays/secondLargestElement.c
Added C code to find out the *Second Largest* Element in the Array.
> chore(C): add find second largest element in array

- algorithms/C/README.md
- algorithms/C/arrays/shuffle_array.c
Language C
New algorithm:
Shuffle an array
> chore(C): add shuffle array algorithm

- algorithms/Java/README.md
- algorithms/Java/strings/isomorphic_strings.java
> chore(Java): add isomorphic strings

- algorithms/Java/Maths/square-root.java
- algorithms/Java/README.md
I have added a Java program to find square root of a number using Binary Search i.e decrease and conquer approach
> chore(Java): add square root using binary search

- algorithms/Python/README.md
- algorithms/Python/strings/find_all_permutations.py
Find all the permutations of a given string in Python
> chore(Python): add find all permutations

- algorithms/Java/README.md
- algorithms/Java/stacks/Next_Greater_Element.java
> chore(Java): add next greater element

- README.md
Added myself in the reviewer's list
Added myself to the reviewer's list in the README.md file
> docs(readme): add Java reviewer

- algorithms/Go/strings/anagram.go
- algorithms/Go/strings/palindrome-permutation.go
> enh(Go): import the string package on anagram

- algorithms/Java/README.md
- algorithms/Java/trees/Left-Leaf-Sum.java
> chore(Java): add left leaf sum binary tree

- algorithms/Java/README.md
Fixed a broken link within the JAVA Readme.
> docs(Java): fix random node of a binary tree link

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/heaps/max-heap.js
max heap data structure implemented with JavaScript.
> chore(JavaScript): add max heap

- docs/en/Tree/min-heap.md
> fix : typos in MinHeap

- algorithms/CPlusPlus/Backtracking/n-queens.cpp
- algorithms/CPlusPlus/README.md
- docs/en/Backtracking/N-Queens.md
N-Queens Problem in C++ using Backtracking. Problem is well explained in Issue: #806  
> chore(CPlusPlus): add n-queens backtracking algorithm

- algorithms/Java/README.md
- algorithms/Java/searching/ternery-search.java
- [*] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
Added Recursive and Iterrative Ternery Search Algorithm in the Java File along with their explaination and Time/Space complexity.  
> chore(Java) : add ternery search

- algorithms/Java/Maths/roman-numerals.java
- algorithms/Java/README.md
I have implemented a roman numeral conversion algorithm in Java that converts integers to roman numerals and vice versa.
None
> chore(Java) : add roman numerals conversion

- algorithms/Java/Maths/roman-numerals.java
corrected the spelling mistake because of which my pull request failed the spell check
> fix(spell) : roman-numerals.java

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/heaps/min-heap.js
- [] My submission has the time complexity of the algorithm
> chore(JavaScript): add min heap

- algorithms/CPlusPlus/Maths/Check-Even_Odd.cpp
- algorithms/Java/Maths/roman-numerals.java
I have added the Algorithm to check for Even and Odd numbers in CplusPlus. I've added two methods for checking Even-Odd, one through Logical And operator (&) and other through Mod operator(%). 
This issue (#501) has been open for a long time and I have decided to close it by making this PR.
> chore(CPlusPlus): add even odd algorithm

- docs/en/Sorting/Bubble-Sort.md
I add the space Complexity also
> enh(en): documentation in bubble sort

- README.md
Hi There,
I hope you're well! I found a small spelling mistake in your README so I went ahead and fixed it for you.
Love the project, keep up the good work!
Kind regards,
Tim
Signed-off-by: Tim Richards thinkingdust@gmail.com
> docs(readme): remove duplicated contribution

- algorithms/Java/Maths/permutation_sequence.java
- algorithms/Java/README.md
Added a new java file in Algorithms/Java/Maths/permutation_sequences.java
- I have added new Algorithm
- Name - Permutation-Sequence
- Language - Java
- You can practice this algorithm online [Permutation-Sequence](https://leetcode.com/problems/permutation-sequence/)
> chore(Java): add permutation sequences

- docs/en/README.md
Added links to missing documentation and rearranged the links in order to make it easier for contributors to add more documentation later down the line.
Issue #289
> docs(en): order the section alphabetically

- algorithms/Python/README.md
- algorithms/Python/arrays/max_sub_array_sum.py
Max Sum of Sub Array 
language: Python
time complexity: O(n)
description: Find the max sum of sub arrays for a given array
> chore(Python): add max sub array sum

- algorithms/CPlusPlus/Arrays/balanced-parenthesis.cpp
- algorithms/CPlusPlus/README.md
- [ x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
Balanced parenthesis problem
Lets understand this with the help of an example:- 
Input: str = “[{}]” 
Output: balanced
Algorithm
* Initialize a character stack st
* Now traverse the string s
* If the current character is a starting bracket (‘(‘ or ‘{‘ or ‘[‘) then push it to stack st.
* If the current character is a closing bracket (‘)’ or ‘}’ or ‘]’) then check if the st is empty or not and also check if the top of the stack is the same opening brackets if it’s true then pop from stack otherwise put ans = …
> chore(CPlusPlus): add balanced parenthesis problem

- algorithms/CPlusPlus/Dynamic-Programming/rod-cutting.cpp
- algorithms/CPlusPlus/README.md
- [Problem Statement](#problem-statement-for-rod-cutting)
- [Examples](#rod-cutting-examples)
- [Optimal Approach](#rod-cutting-optimal-approach)
- [Complexity](#rod-cutting-complexity)
Given a rod of length n and a list of rod prices of length i, where 1 <= i <= n, find the optimal way to cut the rod into smaller rods to maximize profit.
1. prices[] = [1, 5, 8, 9, 10, 17, 17, 20]  
rod length = 4  
Best: Cut the rod into two pieces of length 2 each to gain revenue of 5 + 5 = 10
2. prices[] = [1, 5, 8, 9, 10, 17, 17, 20]
rod length = 8
Best: Cut the rod into two pieces of length 2 and 6 to gain revenue of 5 + 17 = 22
3. prices[] = [3, 5, 8, 9, 10, 17, 17, 20]
rod length = 8
Best: Cut the rod into eight …
> chore(CPlusPlus): add rod cutting problem

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Trie/trie_delete.cpp
- algorithms/CPlusPlus/Trie/trie_insert_search_startWith.cpp
- [] My submission has the time complexity of the algorithm
**Briefly describe the changes in this PR** 
Trie implementation with prefix search is added in the C++ folder.
> chore(CPlusCPlus): add trie algorithms

- .github/workflows/codespell.yml
> chore(codespell): upgrade Github action

- algorithms/Python/README.md
- algorithms/Python/linked_lists/cycle-detection-and-removal-linkedlist.py
Name - Cycle Detection and Removal
Language - Python
> chore(Python): add cycle detection and removal in linkedlist

- algorithms/JavaScript/README.md
- algorithms/JavaScript/src/arrays/two-sum.js
Add two sum problem implementation in JavaScript (#1008)  
***Problem Statement***
Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
You may assume that each input would have exactly one solution, and you may not use the same element twice.
You can return the answer in any order.
This is a competitive platform problem from [leetcode](https://leetcode.com/problems/two-sum/description/)
> chore(JavaScript): add two sum

- algorithms/CPlusPlus/Arrays/specialindex2.cpp
- algorithms/CPlusPlus/README.md
i have contributed by how to find special index in an array 
i.e if an element is deleted from index I  then sum of even index=sum of odd index
(it contains the best approach to solve this problem ,looking forward to contribute more)
> chore(CPlusPlus): add special index in an array

- algorithms/Python/README.md
- algorithms/Python/strings/roman-to-int.py
This program converts a string that represents a valid roman number to its decimal equivalent.
If the string is not a valid roman number, raises a ValueError exception.
> chore(Python): add roman number to int

- CONTRIBUTING.md
- README.md
- docs/en/Searching/Binary-Search.MD
I reviewed and fixed a few grammar and punctuation errors in the .md files.
> docs: fix grammar and punctuation errors

- algorithms/CPlusPlus/README.md
- algorithms/CPlusPlus/Strings/ReverseTheStringWordwise.cpp
> chore(CPlusPlus): add reverse the string wordwise

- docs/en/Searching/Linear-Search.md
I noticed the steps in the algorithm to be continuous which would make it inconvenient for the reader. So, I reformatted the steps to look much cleaner and readable.
> docs(en): enhancement the linear search
